insert into feature_flags (id, is_enabled)
values ('onboardingQR', false)
on conflict (id) do nothing;

insert into relance_profiles (name, tone, min_days_late, max_days_late, payment_score_min) values
  ('Courtois', 'courtois', 1, 14, 80),
  ('Ferme', 'ferme', 15, 45, 40),
  ('Humoristique', 'humoristique', 1, 30, 90);

insert into closing_task_templates (id, code, label, section, freq, legal_ref, default_due) values
  (gen_random_uuid(),'M-OPEN-001','Extourner débiteurs / fournisseurs N-1','Ouverture','monthly','CO art. 958b',1),
  (gen_random_uuid(),'M-DEP-003','Passer amortissements mensuels','Amort. & provisions','monthly','OFD 2019',3),
  (gen_random_uuid(),'M-BANK-004','Lettrer paiements clients non affectés','Clients','monthly','CO art. 958d',2),
  (gen_random_uuid(),'M-STAT-005','Analyser variations majeures du bilan','Analyse','monthly',NULL,5),
  (gen_random_uuid(),'M-ACC-006','Provision 13ᵉ salaire (1/12)','Transitoires','monthly','CO art. 960e',2),
  (gen_random_uuid(),'M-VAT-007','Calculer TVA à payer ou à récupérer','TVA','monthly','LTVA art. 37',4),
  (gen_random_uuid(),'M-SAL-008','Enregistrer salaires et charges sociales','Salaires','monthly','CO art. 324a',2),
  (gen_random_uuid(),'M-PAY-009','Déclarer et payer charges sociales','Salaires','monthly','LAVS',5),
  (gen_random_uuid(),'M-CLI-010','Revue créances douteuses','Clients','monthly','CO art. 960a',6),
  (gen_random_uuid(),'M-CLI-011','Relancer clients >30 jours','Clients','monthly',NULL,6),
  (gen_random_uuid(),'M-FOU-012','Lettrer factures fournisseurs en suspens','Fournisseurs','monthly',NULL,4),
  (gen_random_uuid(),'M-FOU-013','Revue factures reçues non parvenues','Fournisseurs','monthly','CO art. 960a',5),
  (gen_random_uuid(),'M-IMP-014','Provision impôts cantonaux et communaux','Impôts','monthly','CO art. 960e',7),
  (gen_random_uuid(),'M-CAIS-015','Contrôle mouvements de caisse','Caisse & banques','monthly',NULL,1),
  (gen_random_uuid(),'M-DEP-016','Calcul amortissements exceptionnels','Amort. & provisions','monthly','OFD 2019',8),
  (gen_random_uuid(),'M-ETAT-017','Mettre à jour tableau de bord de trésorerie','Trésorerie','monthly',NULL,4),
  (gen_random_uuid(),'M-TAX-018','Actualiser taux de change','Général','monthly',NULL,3),
  (gen_random_uuid(),'M-ACC-019','Comptabiliser intérêts bancaires','Caisse & banques','monthly',NULL,4),
  (gen_random_uuid(),'M-INV-020','Inventaire tournant des stocks','Stocks','monthly','CO art. 960c',9),
  (gen_random_uuid(),'M-INV-021','Analyse variation de stock','Stocks','monthly',NULL,9),
  (gen_random_uuid(),'M-FIN-022','Rapprochement prêts et intérêts','Financement','monthly',NULL,6),
  (gen_random_uuid(),'M-IT-023','Sauvegarde dossiers comptables','Général','monthly',NULL,1),
  (gen_random_uuid(),'M-GEN-024','Vérifier équilibrage des comptes généraux','Général','monthly',NULL,5),
  (gen_random_uuid(),'M-PROV-025','Constituer provisions charges à payer','Transitoires','monthly','CO art. 960e',6),
  (gen_random_uuid(),'M-REV-026','Constater produits à recevoir','Transitoires','monthly','CO art. 958b',6),
  (gen_random_uuid(),'M-CAUS-027','Contrôle cohérence analytique','Analyse','monthly',NULL,7),
  (gen_random_uuid(),'A-SEC-001','Vérifier liste titres vs compte 13xx','Titres-participations','annual','FER 29',30),
  (gen_random_uuid(),'A-STK-002','Inventaire physique annuel des stocks','Stocks','annual','CO art. 958c',30),
  (gen_random_uuid(),'A-CLI-003','Confirmation saldos clients','Clients','annual','CO art. 958d',30),
  (gen_random_uuid(),'A-LEG-004','Contrôle réserves capital','Dossier & légaux','annual','CO 960f',45),
  (gen_random_uuid(),'A-FOU-005','Confirmation saldos fournisseurs','Fournisseurs','annual','CO art. 958d',30),
  (gen_random_uuid(),'A-FIN-006','Revue engagements hors bilan','Financement','annual',NULL,60),
  (gen_random_uuid(),'A-TAX-007','Préparer déclaration TVA annuelle','TVA','annual','LTVA art. 72',60),
  (gen_random_uuid(),'A-ACC-008','Calcul impôt sur le résultat','Impôts','annual','CO art. 958b',60),
  (gen_random_uuid(),'A-PROV-009','Revue provisions long terme','Amort. & provisions','annual','CO art. 960e',60),
  (gen_random_uuid(),'A-ACT-010','Test de dépréciation des actifs','Immobilisations','annual','FER 27',60),
  (gen_random_uuid(),'A-DEP-011','Réviser plan d''amortissement','Amort. & provisions','annual','OFD 2019',60),
  (gen_random_uuid(),'A-CAIS-012','Inventaire espèces et titres','Caisse & banques','annual',NULL,30),
  (gen_random_uuid(),'A-ORG-013','Actualiser registre des associés','Dossier & légaux','annual','CO art. 790',90),
  (gen_random_uuid(),'A-ANL-014','Préparer annexes CO / FER','Rapport','annual','CO art. 959c',90),
  (gen_random_uuid(),'A-AG-015','Organiser assemblée générale','Rapport','annual','CO art. 699',90),
  (gen_random_uuid(),'A-REP-016','Établir rapport de gestion','Rapport','annual','CO art. 961c',90),
  (gen_random_uuid(),'A-SUI-017','Planifier objectifs exercice suivant','Analyse','annual',NULL,90),
  (gen_random_uuid(),'A-CON-018','Revue contrats & engagements','Dossier & légaux','annual',NULL,60),
  (gen_random_uuid(),'A-INV-019','Évaluer participations et immobilisations','Titres-participations','annual','FER 30',60),
  (gen_random_uuid(),'A-BANK-020','Confirmer soldes bancaires annuels','Caisse & banques','annual','CO art. 958d',30),
  (gen_random_uuid(),'A-DOS-001','Décomptes TVA et réconciliation annuelle','Dossier Annexe','annual','TVA 8,1 %',30),
  (gen_random_uuid(),'B-DOS-002','Réconciliation des salaires et charges sociales','Dossier Annexe','annual','AVS/LPP',30),
  (gen_random_uuid(),'C-DOS-003','Trésorerie - confirmations banques & caisse','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'D-DOS-004','Créances résultant de la vente de biens et prestations','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'E-DOS-005','Autres créances à court terme','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'F-DOS-006','Stocks & prestations non facturées','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'F1-DOS-007','Stocks & travaux en cours','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'G-DOS-008','Actifs de régularisation','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'H-DOS-009','Immobilisations financières','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'I-DOS-010','Participations','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'J-DOS-011','Créances/dettes envers détenteurs de participations','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'J1-DOS-012','Créances/dettes envers détenteurs de parts','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'J2-DOS-013','Créances/dettes envers sociétés du groupe','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'K-DOS-014','Immobilisations corporelles','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'L-DOS-015','Immobilisations incorporelles','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'M-DOS-016','Dettes résultant de l''achat de biens & prestations','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'N-DOS-017','Dettes CT portant intérêts','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'O-DOS-018','Autres dettes à court terme','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'P-DOS-019','Passifs de régularisation & provisions CT','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'Q-DOS-020','Dettes LT portant intérêts','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'R-DOS-021','Autres dettes à long terme','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'S-DOS-022','Provisions CT & LT','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'T-DOS-023','Capitaux propres','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'V-DOS-024','Charges & produits extraordinaires / antérieurs','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'W-DOS-025','Analyse du compte d''exploitation','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'X-DOS-026','Part privée véhicule & prestations à soi-même','Dossier Annexe','annual',NULL,30),
  (gen_random_uuid(),'Z-DOS-027','Informations pour l''annexe du bilan','Dossier Annexe','annual',NULL,30);
